apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: hashicorp/http-echo
          args:
            - "-text=api running"
          ports:
            - containerPort: 5678
